# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true

# Plugins
modmuss50_mod_publish_version        = 0.8.4
spongepowered_mixin_version          = 0.7-SNAPSHOT
fabric_loom_version                  = 1.10-SNAPSHOT
spotless_version                     = 7.0.0.BETA3
parchment_minecraft                  = 1.21.1
parchment_version                    = 2024.11.17

# Project
modrinthID				             = soJ7aVav
curseforgeID			             = 919216
projectSlug				             = diabolical-delights

# Common
java_version                         = 21
minecraft_version                    = 1.21.1
neoform_version                      = 1.21.1-20240808.144430

# NeoForge
loader_version_range                 = [3,)
mapping_channel                      = official
mapping_version                      = 1.21.1
minecraft_version_range              = [1.21.1, 1.21.2)
neo_moddev                           = 2.0.27-beta
neo_version                          = 21.1.209
neo_version_range                    = [21,)

# Fabric
fabric_version                       = 0.116.6+1.21.1
fabric_loader_version                = 0.17.2

# Libs
modmenu_version                      = 11.0.2
azurelib_version                     = 3.1.0

# Mod options
group                                = mod.azure.diabolicaldelights
mod_name                             = Diabolical Delights
mod_author                           = AzureDoom
mod_id                               = diabolicaldelights
mod_license                          = MIT
mod_description                      = Diabolical Delights adds a delightful element of surprise and chaos via the Jack O'Bomb item!
mod_credits                          = AzureDoom
mod_logo                             = icon.png
mod_url                              = https://www.curseforge.com/minecraft/mc-mods/diabolical-delights
mod_issues                           = https://github.com/AzureDoom/Diabolical-Delights/issues
mod_sources                          = https://github.com/AzureDoom/Diabolical-Delights/
version                              = 1.0.1
